# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61a8a9276c1d4c155d6425b42a6e9fb51f729ecb1e0899e43a47f80642ff1b230bfb909a771533b0a7abe8ed2adb764d9470b2374e2f9941f8b051eeab9c52d

test:
  secret_key_base: 51b6b17ea08fcc97b6d5e9ecb1f22bb6955b783fedd735a7e440905c430f9391cf7c95ddd8ddc4f7a0aae724a9f92cd79de8ac1976ef8bf22ea1211c5f6ba6a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
